### PR TITLE
Read only user preferences for non admins

### PR DESCRIPTION
**Pull request by tannazma**
Before changing the formula I commited changes for user preferences, only admins can change the user preferences for the users and users can only see the user preference setting

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
I assume this also prevents someone from saving it even if they edit the HTML and remove `disabled`?

**Comment by tannazma** [comment]
I have to test it out😁but good point thanks

**Comment by tannazma** [comment]
I checked if the user can edit the data if it is disabled, and it turned out read-only works better than disabled, even though the UI is changed and the changed data will be sent to the backend but the changes never apply

**Review by SleeplessByte — APPROVED** [review]

**Comment by tannazma** [comment]
It turned out that even with read-only, the user can edit HTML... I am trying to find a way to show the none-admin users the info but maybe not in the form

**Pull request merged**
